// Hebrew names for every country in the world-atlas 110m dataset (Natural Earth names).
export const COUNTRIES_HE: Record<string, string> = {
  Afghanistan: "אפגניסטן",
  Albania: "אלבניה",
  Algeria: "אלג׳יריה",
  Angola: "אנגולה",
  Antarctica: "אנטארקטיקה",
  "Antigua and Barb.": "אנטיגואה וברבודה",
  Argentina: "ארגנטינה",
  Armenia: "ארמניה",
  Australia: "אוסטרליה",
  Austria: "אוסטריה",
  Azerbaijan: "אזרבייג׳ן",
  Bahamas: "בהאמה",
  "The Bahamas": "בהאמה",
  Bahrain: "בחריין",
  Bangladesh: "בנגלדש",
  Barbados: "ברבדוס",
  Belarus: "בלארוס",
  Belgium: "בלגיה",
  Belize: "בליז",
  Benin: "בנין",
  Bhutan: "בהוטן",
  Bolivia: "בוליביה",
  "Bosnia and Herz.": "בוסניה והרצגובינה",
  Botswana: "בוצואנה",
  Brazil: "ברזיל",
  Brunei: "ברוניי",
  Bulgaria: "בולגריה",
  "Burkina Faso": "בורקינה פאסו",
  Burundi: "בורונדי",
  Cambodia: "קמבודיה",
  Cameroon: "קמרון",
  Canada: "קנדה",
  "Central African Rep.": "הרפובליקה המרכז־אפריקאית",
  Chad: "צ׳אד",
  Chile: "צ׳ילה",
  China: "סין",
  Colombia: "קולומביה",
  "Dem. Rep. Congo": "הרפובליקה הדמוקרטית של קונגו",
  Congo: "קונגו",
  "Costa Rica": "קוסטה ריקה",
  "Côte d'Ivoire": "חוף השנהב",
  "Ivory Coast": "חוף השנהב",
  Croatia: "קרואטיה",
  Cuba: "קובה",
  Cyprus: "קפריסין",
  "N. Cyprus": "צפון קפריסין",
  "Czech Rep.": "צ׳כיה",
  Czechia: "צ׳כיה",
  Denmark: "דנמרק",
  Djibouti: "ג׳יבוטי",
  Dominica: "דומיניקה",
  "Dominican Rep.": "הרפובליקה הדומיניקנית",
  Ecuador: "אקוודור",
  Egypt: "מצרים",
  "El Salvador": "אל סלבדור",
  "Eq. Guinea": "גינאה המשוונית",
  Eritrea: "אריתריאה",
  Estonia: "אסטוניה",
  eSwatini: "אסוואטיני",
  Swaziland: "סווזילנד",
  Ethiopia: "אתיופיה",
  "Falkland Is.": "איי פוקלנד",
  "Falkland Islands": "איי פוקלנד",
  Fiji: "פיג׳י",
  Finland: "פינלנד",
  France: "צרפת",
  "Fr. S. Antarctic Lands": "אדמות צרפתיות דרומיות",
  Gabon: "גבון",
  Gambia: "גמביה",
  "The Gambia": "גמביה",
  Georgia: "גאורגיה",
  Germany: "גרמניה",
  Ghana: "גאנה",
  Greece: "יוון",
  Greenland: "גרינלנד",
  Grenada: "גרנדה",
  Guatemala: "גואטמלה",
  Guinea: "גינאה",
  "Guinea-Bissau": "גינאה ביסאו",
  Guyana: "גויאנה",
  Haiti: "האיטי",
  Honduras: "הונדורס",
  Hungary: "הונגריה",
  Iceland: "איסלנד",
  India: "הודו",
  Indonesia: "אינדונזיה",
  Iran: "איראן",
  Iraq: "עיראק",
  Ireland: "אירלנד",
  Israel: "ישראל",
  Italy: "איטליה",
  Jamaica: "ג׳מייקה",
  Japan: "יפן",
  Jordan: "ירדן",
  Kazakhstan: "קזחסטן",
  Kenya: "קניה",
  Kosovo: "קוסובו",
  Kuwait: "כווית",
  Kyrgyzstan: "קירגיזסטן",
  Laos: "לאוס",
  Latvia: "לטביה",
  Lebanon: "לבנון",
  Lesotho: "לסוטו",
  Liberia: "ליבריה",
  Libya: "לוב",
  Lithuania: "ליטא",
  Luxembourg: "לוקסמבורג",
  Madagascar: "מדגסקר",
  Malawi: "מלאווי",
  Malaysia: "מלזיה",
  Mali: "מאלי",
  Mauritania: "מאוריטניה",
  Mexico: "מקסיקו",
  Moldova: "מולדובה",
  Mongolia: "מונגוליה",
  Montenegro: "מונטנגרו",
  Morocco: "מרוקו",
  Mozambique: "מוזמביק",
  Myanmar: "מיאנמר",
  Namibia: "נמיביה",
  Nepal: "נפאל",
  Netherlands: "הולנד",
  "New Caledonia": "קלדוניה החדשה",
  "New Zealand": "ניו זילנד",
  Nicaragua: "ניקרגואה",
  Niger: "ניז׳ר",
  Nigeria: "ניגריה",
  "North Korea": "צפון קוריאה",
  "Dem. Rep. Korea": "צפון קוריאה",
  "North Macedonia": "צפון מקדוניה",
  Macedonia: "מקדוניה",
  Norway: "נורבגיה",
  Oman: "עומאן",
  Pakistan: "פקיסטן",
  Palestine: "פלסטין",
  Panama: "פנמה",
  "Papua New Guinea": "פפואה גינאה החדשה",
  Paraguay: "פרגוואי",
  Peru: "פרו",
  Philippines: "הפיליפינים",
  Poland: "פולין",
  Portugal: "פורטוגל",
  "Puerto Rico": "פוארטו ריקו",
  Qatar: "קטר",
  Romania: "רומניה",
  Russia: "רוסיה",
  Rwanda: "רואנדה",
  "Saudi Arabia": "ערב הסעודית",
  Senegal: "סנגל",
  Serbia: "סרביה",
  "Republic of Serbia": "סרביה",
  "Sierra Leone": "סיירה לאון",
  Singapore: "סינגפור",
  Slovakia: "סלובקיה",
  Slovenia: "סלובניה",
  "Solomon Is.": "איי שלמה",
  "Solomon Islands": "איי שלמה",
  Somalia: "סומליה",
  Somaliland: "סומלילנד",
  "South Africa": "דרום אפריקה",
  "South Korea": "דרום קוריאה",
  "Republic of Korea": "דרום קוריאה",
  "S. Sudan": "דרום סודן",
  "South Sudan": "דרום סודן",
  Spain: "ספרד",
  "Sri Lanka": "סרי לנקה",
  Sudan: "סודן",
  Suriname: "סורינאם",
  Sweden: "שבדיה",
  Switzerland: "שווייץ",
  Syria: "סוריה",
  Taiwan: "טייוואן",
  Tajikistan: "טג׳יקיסטן",
  Tanzania: "טנזניה",
  "United Republic of Tanzania": "טנזניה",
  Thailand: "תאילנד",
  "Timor-Leste": "טימור המזרחית",
  Togo: "טוגו",
  "Trinidad and Tobago": "טרינידד וטובגו",
  Tunisia: "תוניסיה",
  Turkey: "טורקיה",
  Turkmenistan: "טורקמניסטן",
  Uganda: "אוגנדה",
  Ukraine: "אוקראינה",
  "United Arab Emirates": "איחוד האמירויות הערביות",
  "United Kingdom": "בריטניה",
  "United States of America": "ארה״ב",
  "United States": "ארה״ב",
  Uruguay: "אורוגוואי",
  Uzbekistan: "אוזבקיסטן",
  Vanuatu: "ונואטו",
  Venezuela: "ונצואלה",
  Vietnam: "וייטנאם",
  "W. Sahara": "סהרה המערבית",
  "Western Sahara": "סהרה המערבית",
  Yemen: "תימן",
  Zambia: "זמביה",
  Zimbabwe: "זימבבואה",
  Kiribati: "קיריבטי",
  Tonga: "טונגה",
  "Saint Lucia": "סנט לוסיה",
  "St. Vin. and Gren.": "סנט וינסנט",
  "Saint Kitts and Nevis": "סנט קיטס ונוויס",
};

export const heCountryName = (name: string): string => COUNTRIES_HE[name] ?? name;